spring:
#  freemarker:
#    template-loader-path: classpath:/templates/
#    prefer-file-system-access: false
  application:
    name: euerka-server-cluster
#安全认证的配置      security:
    basic: 
      enabled: true#    user:#      name: root
#      password: 123456
      
#端口    
server:  port: 8761
  
eureka:  instance:    hostname: xz01
  client:
#由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己  ,true 集群模式    register-with-eureka: true 
#由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetch-registry: true       
    service-url:#      defaultZone: http://root:123456@xz02:8762/eureka/
      defaultZone: http://xz02:8762/eureka/      

