spring:
  application:
    name: euerka-server  
#端口    
server:  port: 8762
  
eureka:  instance:    hostname: xz01
  client:
#由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己  ,true 集群模式    register-with-eureka: false 
#由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetch-registry: false       
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/      

